version: '3.8'

services:
  server:
    image: sbtscala/scala-sbt:eclipse-temurin-17.0.4_1.7.1_3.2.0
    build: .
    command:
      sbt run
    ports:
      - "6000:6000"
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - network-api
    volumes:
      - ../build.sbt:/root/build.sbt
      - ../src:/root/src/

  postgres:
    image: postgres
    container_name: tema2
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
      - ../sql:/docker-entrypoint-initdb.d
    env_file: global-variables.env
    ports:
      - "5432:5432"
    networks:
      - network-api
      - network-gui

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    env_file: global-variables.env
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "5050:80"
    networks:
      - network-gui
    restart: unless-stopped
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres:
    driver: local
  pgadmin-data:
  server:
    driver: local

networks:
  network-api:
    name: network-api
  network-gui:
    name: network-gui
